### PR TITLE
Add app error field names to response for marking in the UI

### PR DESCRIPTION
**Pull request by UsmannK**
For form validation

### CODE REVIEW

**Comment by kedarv** [comment]
Isn't this a breaking change without a corresponding frontend PR? Also @nickysemenza why are we building validation ourselves rather than using the validator class?

**Comment by nickysemenza** [comment]
No, only the exec panel uses this info, and it's ok if that temporarily breaks 
And this isn't even really 'validation' just 'completeness' 🤷‍♂️

**Comment by UsmannK** [comment]
I don't think the renamed api is actually used anywhere, right?

**Comment by kedarv** [comment]
Oh yeah you're right, we don't use this data at all right now..
Feel like this is fine for now but we should really really be using the builtin validation class for the future. go ahead and merge for now 👍

**Pull request merged**
